name: hardhat use artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["hardhat create artifact"] # The name of the workflow that creates the artifact
    types:
      - completed

jobs:
  test_on_linux:
    name: Test on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: module-artifact # The name of the artifact you uploaded
      - name: Check cli command
        run: node index.js test
