name: hardhat use artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_on_linux:
    name: Test on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: module-artifact # The name of the artifact you uploaded
      # - name: Check cli command
      #   run: node index.js test
      - name: Download latest artifact from TEST REPO
        run: |
          # Fetch the list of artifacts from Repo hh-test-repo-artif
          ARTIFACTS_URL="https://api.github.com/repos/ChristopherDedominici/hh-test-repo-artif/actions/artifacts"
          ARTIFACTS_JSON=$(curl $ARTIFACTS_URL)

          # Extract the download URL of the latest artifact
          DOWNLOAD_URL=$(echo $ARTIFACTS_JSON | jq -r '.artifacts[0].archive_download_url')

          # Download the artifact
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o artifact.zip $DOWNLOAD_URL
      - name: Unzip artifact
        run: unzip artifact.zip
      # - name: Check cli command
      #   run: node index.js test
